### ISSUE TITLE
Upgrade to projectV2 GraphQL API

### ISSUE THREAD

**Issue by vladanpaunovic** [getsentry/sentry-project-automation#1]
### Official statement from Github
> The ProjectNext API is deprecated in favour of the more capable ProjectV2 API. Follow the ProjectV2 guide at https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/, to find a suitable replacement. Removal on 2022-10-01 UTC.

As Github is deprecating their [ProjectNext](https://docs.github.com/en/graphql/reference/objects#projectnext) GraphQL API in favour of a more stable [ProjectV2](https://docs.github.com/en/graphql/reference/objects#projectv2) API we should update this project accordingly.

### Risks
Not doing this before 2022-10-01 will cause our projects on Github to stop syncing with our repositories.

### Tasks
- [ ] Rename all instances of `ProjectNext` to `ProjectV2` and double check the success of it
- [ ] Double check whether it is possible or not to query archived items with the new API

**Comment by HazAT** [comment]
Done
